// About Page
export const GET_ABOUT_DATA_PENDING = "GET_ABOUT_DATA_PENDING";
export const GET_ABOUT_DATA_REJECTED = "GET_ABOUT_DATA_REJECTED";
export const GET_ABOUT_DATA_FULFILLED = "GET_ABOUT_DATA_FULFILLED";
// CMS and Auth
export const LOG_IN_USER = "LOG_IN_USER";
export const LOG_IN_USER_REJECTED = "LOG_IN_USER_REJECTED";
export const LOG_OUT = "LOG_OUT";
export const CLEAR_LOGGED_USER = "CLEAR_LOGGED_USER";
export const GET_USER = "GET_USER";
