// About Page
export const GET_ABOUT_DATA_PENDING = 'GET_ABOUT_DATA_PENDING';
export const GET_ABOUT_DATA_REJECTED = 'GET_ABOUT_DATA_REJECTED';
export const GET_ABOUT_DATA_FULFILLED = 'GET_ABOUT_DATA_FULFILLED';
// CMS and Auth
export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_IN_USER_REJECTED = 'LOG_IN_USER_REJECTED';
export const LOG_OUT = 'LOG_OUT';
export const CLEAR_LOGGED_USER = 'CLEAR_LOGGED_USER';
export const GET_USER = 'GET_USER';
export const LOG_IN_USER_END = 'LOG_IN_USER_END';
// About
export const GET_ABOUT_CMS_DATA_PENDING = 'GET_ABOUT_CMS_DATA_PENDING';
export const GET_ABOUT_CMS_DATA_REJECTED = 'GET_ABOUT_CMS_DATA_REJECTED';
export const GET_ABOUT_CMS_DATA_FULFILLED = 'GET_ABOUT_CMS_DATA_FULFILLED';
// CMS About
export const UPDATE_ABOUT_CMS_DATA_PENDING = 'UPDATE_ABOUT_CMS_DATA_PENDING';
export const UPDATE_ABOUT_CMS_DATA_REJECTED = 'UPDATE_ABOUT_CMS_DATA_REJECTED';
export const UPDATE_ABOUT_CMS_DATA_FULFILLED = 'UPDATE_ABOUT_CMS_DATA_FULFILLED';
// Language
export const SWICH_TO_ENG = 'SWICH_TO_ENG';
export const SWICH_TO_PL = 'SWICH_TO_PL';
// Projects
export const GET_PROJECTS_DATA_PENDING = 'GET_PROJECTS_DATA_PENDING';
export const GET_PROJECTS_DATA_REJECTED = 'GET_PROJECTS_DATA_REJECTED';
export const GET_PROJECTS_DATA_FULFILLED = 'GET_PROJECTS_DATA_FULFILLED';

// CMS Projects
export const GET_PROJECTS_CMS_DATA_PENDING = 'GET_PROJECTS_CMS_DATA_PENDING';
export const GET_PROJECTS_CMS_DATA_REJECTED = 'GET_PROJECTS_CMS_DATA_REJECTED';
export const GET_PROJECTS_CMS_DATA_FULFILLED = 'GET_PROJECTS_CMS_DATA_FULFILLED';

export const ADD_PROJECT_CMS_DATA_PENDING = 'ADD_PROJECT_CMS_DATA_PENDING';
export const ADD_PROJECT_CMS_DATA_REJECTED = 'ADD_PROJECT_CMS_DATA_REJECTED';
export const ADD_PROJECT_CMS_DATA_FULFILLED = 'ADD_PROJECT_CMS_DATA_FULFILLED';

export const TOGGLE_PROJECT_CMS_DATA_PENDING = 'TOGGLE_PROJECT_CMS_DATA_PENDING';
export const TOGGLE_PROJECT_CMS_DATA_REJECTED = 'TOGGLE_PROJECT_CMS_DATA_REJECTED';
export const TOGGLE_PROJECT_CMS_DATA_FULFILLED = 'TOGGLE_PROJECT_CMS_DATA_FULFILLED';

// Contact
export const GET_CONTACT_DATA_PENDING = 'GET_CONTACT_DATA_PENDING';
export const GET_CONTACT_DATA_REJECTED = 'GET_CONTACT_DATA_REJECTED';
export const GET_CONTACT_DATA_FULFILLED = 'GET_CONTACT_DATA_FULFILLED';

export const SEND_EMAIL_PENDING = 'SEND_EMAIL_PENDING';
export const SEND_EMAIL_REJECTED = 'SEND_EMAIL_REJECTED';
export const SEND_EMAIL_FULFILLED = 'SEND_EMAIL_FULFILLED';

export const GET_EMAILS_DATA_PENDING = 'GET_EMAILS_DATA_PENDING';
export const GET_EMAILS_DATA_REJECTED = 'GET_EMAILS_DATA_REJECTED';
export const GET_EMAILS_DATA_FULFILLED = 'GET_EMAILS_DATA_FULFILLED';

export const DELETE_EMAIL_PENDING = 'DELETE_EMAIL_PENDING';
export const DELETE_EMAIL_REJECTED = 'DELETE_EMAIL_REJECTED';
export const DELETE_EMAIL_FULFILLED = 'DELETE_EMAIL_FULFILLED';
